services:
  - type: web
    name: vasundhara-pro9
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FASHN_API_KEY
        sync: false
